### ISSUE TITLE
How to handle the npm packages wrote with Es6?

### ISSUE THREAD

**Issue by Creemli** [taobaofed/react-web#138]
When I trying to convert an existing project to web, it turns out to be the error:  
```javascript
index.js:3Uncaught SyntaxError: Unexpected token import
```
and this file is in the /node_modules/ directory. (I found many react-native packages are wrote with es6)

**Comment by brainpoint** [comment]
同问, 使用node v6来处理都会出错

**Comment by flyskywhy** [comment]
@Creemli @brainpoint , this issue was resolved in latest github.com/taobaofed/react-web.git , with the change of webpack.config.js (`exclude: [/node_modules/]` to `exclude: /(node_modules\/(?!react))/`), you can directly use react-native packages wroted with es6 e.g. react-native-scrollable-tab-view

You can

    react-web init <ExistedProjectDir>

and then

    npm install --save git+https://github.com/taobaofed/react-web.git 

now, or when @yuanyan publish the latest react-web-cli , you can just

    react-web init --version git+https://github.com/taobaofed/react-web.git
