### ISSUE TITLE
Uncaught TypeError: Cannot read property 'create' of undefined (StyleSheet)

### ISSUE THREAD

**Issue by brainpoint** [taobaofed/react-web#141]
react-native 版本号为 0.30; 
react-web bundle 之后,打开index.html页面, 提示错误, StyleSheet找不到这个模块??

**Comment by brainpoint** [comment]
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TouchableHighlight,
  // Navigator,
  TouchableOpacity
} from 'react-native';

所有的react-native中的模块都为 undefined, 是不是webpack配置问题, 我已经将配置中 react-native的别名设置成react-web了, 还是无法解决

**Comment by yuanyan** [comment]
尝试把react-native改为React-web是否生效？

**Comment by brainpoint** [comment]
在win平台上没有问题, 在mac上出问题, node版本号相同, 不知道这么回事

**Comment by jpgpereira** [comment]
@yuanyan I'm having this problem as well, and didn't understand what was the fix or why the issue was closed, Google translate didn't help much as well. I'm using the react-native-meteor package and it says that StyleSheet is undefined, despite the import. I've created the alias to react-web on the webpack.config file
