### ISSUE TITLE
打算支持server端渲染吗？

### ISSUE THREAD

**Issue by WeweTom** [taobaofed/react-web#186]
现在 react-web 转的代码略大，启动时间比较长。所以，是否可以将首屏进行server端渲染？

**Comment by cssivision** [comment]
请在 webpack 的配置文件中移除掉 devtool 字段，避免生成 sourcemap，这样会保证生成的文件很小

**Comment by WeweTom** [comment]
去掉了 sourcemap 的，你说的很小是多大？我打包一个简单的helloworld有750kb+

**Comment by brainpoint** [comment]
可以使用插件再进行mini化---------------
李鹏翔
brainpoint
            在2017年02月12日 16:50，jinweitang 写道： 去掉了 sourcemap 的，你说的很小是多大？我打包一个简单的helloworld有750kb+

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/taobaofed/react-web","title":"taobaofed/react-web","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/taobaofed/react-web"}},"updates":{"snippets":[{"icon":"PERSON","message":"@WeweTom in #186: 去掉了 sourcemap 的，你说的很小是多大？我打包一个简单的helloworld有750kb+"}],"action":{"name":"View Issue","url":"https://github.com/taobaofed/react-web/issues/186#issuecomment-279204963"}}}

**Comment by WeweTom** [comment]
@brainpoint 能否说详细点。。。

**Comment by brainpoint** [comment]
在webpack 中使用 uglifyJs---------------
李鹏翔
brainpoint
            在2017年02月12日 17:20，jinweitang 写道： @brainpoint 能否说详细点。。。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/taobaofed/react-web","title":"taobaofed/react-web","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/taobaofed/react-web"}},"updates":{"snippets":[{"icon":"PERSON","message":"@WeweTom in #186: @brainpoint 能否说详细点。。。"}],"action":{"name":"View Issue","url":"https://github.com/taobaofed/react-web/issues/186#issuecomment-279206247"}}}
