### ISSUE TITLE
请问listview在滑动的时候,如何逐渐隐藏safari的地址栏,工具栏?

### ISSUE THREAD

**Issue by unakayou** [taobaofed/react-web#189]
请问listview在滑动的时候,如何逐渐隐藏safari的地址栏,工具栏? 

貌似safari接收不到这个滑动?minimal-ui也不可以用了.怎么办呢?谢谢

**Comment by brainpoint** [comment]
关注

**Comment by cssivision** [comment]
这是 safari 自带的行为

**Comment by brainpoint** [comment]
貌似最外层view的高度大于屏幕高度就可以---------------
李鹏翔
brainpoint
            在2017年02月20日 15:07，cssivision 写道： 这是 safari 自带的行为

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/taobaofed/react-web","title":"taobaofed/react-web","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/taobaofed/react-web"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cssivision in #189: 这是 safari 自带的行为"}],"action":{"name":"View Issue","url":"https://github.com/taobaofed/react-web/issues/189#issuecomment-281003281"}}}
