### ISSUE TITLE
scrollView.scrollEventThrottle 定义错误?

### ISSUE THREAD

**Issue by brainpoint** [taobaofed/react-web#197]
react-native: scrollEventThrottle number #

这个属性控制在滚动过程中，scroll事件被调用的频率（**单位是每秒事件数量**）。更大的数值能够更及时的跟踪滚动位置

好像react-web对scrollEventThrottle的处理是相反的, 数值越小处理越实时?

**Comment by cssivision** [comment]
react-native官方有对应的描述 https://facebook.github.io/react-native/releases/0.31/docs/scrollview.html#scrolleventthrottle : A lower number yields better accuracy for code that is tracking the scroll position, but can lead to scroll performance problems due to the volume of information being send over the bridge

**Comment by cssivision** [comment]
react-web 和 react-native 是一样的，代码如下：https://github.com/taobaofed/react-web/blob/master/Libraries/ScrollView/ScrollView.web.js#L160
