### ISSUE TITLE
空项目build出的js好大啊，有4MB+，有能缩减的方案吗？

### ISSUE THREAD

**Issue by sopaco** [taobaofed/react-web#216]

**Comment by diytz** [comment]
webpack.config.js中设置devtool: false

**Comment by cssivision** [comment]
the [devtool](https://webpack.github.io/docs/configuration.html#devtool) is used to debug, because the existence of suurce map, `build.js` file maybe over 4M. for production please remove devtool.

**Comment by brainpoint** [comment]
webpack压缩方案可到600kb内李鹏翔
brainpoint
            在2017年02月03日 14:06，cssivision 写道： Closed #216.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/taobaofed/react-web","title":"taobaofed/react-web","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/taobaofed/react-web"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #216."}],"action":{"name":"View Issue","url":"https://github.com/taobaofed/react-web/issues/216#event-947608941"}}}
