### ISSUE TITLE
ListView的cell是否可实现重用

### ISSUE THREAD

**Issue by brainpoint** [taobaofed/react-web#226]
在cell数量很多时, 因没有cell重用机制导致效率低下; 是否可实现cell重用

**Comment by cssivision** [comment]
你可以通过两个方式来优化渲染的性能，

1，Only re-render changed rows - the rowHasChanged function provided to the data source tells the ListView if it needs to re-render a row because the source data has changed - see ListViewDataSource for more details.

2，Rate-limited row rendering - By default, only one row is rendered per event-loop (customizable with the pageSize prop). This breaks up the work into smaller chunks to reduce the chance of dropping frames while rendering rows.
