### ISSUE TITLE
Image resizeMode support

### ISSUE THREAD

**Issue by gre** [taobaofed/react-web#40]
It doesn't seem resizeMode is supported, right?
Do you have plan for this? I know that CSS can do things background-size:contain, but that's only on a background. not sure how to address this while keeping the `<img/>`, but maybe with a container (that would use the Image style) and some CSS transforms on the image?

**Comment by yuanyan** [comment]
Image component in react-web support resizeMode property.  See: https://github.com/taobaofed/react-web/blob/master/Libraries/Image/Image.web.js#L34

**Comment by gre** [comment]
mmh I've experience cases when it doesn't behave the same. I'll need to figure a simple code to reproduce.

**Comment by pmead** [comment]
I wonder if this is related to this [commit](https://github.com/dubit/react-web/commit/25e667637ba5146ec153fcdf3f0294d37af51cdb)

If so and the new behavior is decide I'll make a pull request.

I found that a default style of `{ opacity: 1 }` was being applied to my image and so when I added renderMode through a style it thought `<Image style={styles.imageStyle}/>` was an array of styles.

But because Image (in some cases) returns a dom element `<img>` instead of a native component `<View>` the style property isn't processed and becomes `0:[object Object], 1: [object Object]`

Anyway the fix was to remove the native check.

**Comment by gre** [comment]
good catch. But I don't think we should remove the whitelisting of this..
I'm the author of this change and this was breaking for me: when you use your own react component that accept a `style`, it should not be overrided by react-web internal, it's way too intrusive. E.g. it breaks the use of libraries like react-canvas.

**Comment by gre** [comment]
Still, I don't understand where the bug is, because it looks like `Image` will just forward the `...props` to `<img/>` so it should already have been style processed, why is this not the case ?

**Comment by pmead** [comment]
React-dom doesn't support Arrays of style objects. That is a feature of react-native only.

**Comment by pmead** [comment]
Is the problem with #37 the fact that it tries to process a functor? In which case `=== 'object'` is your problem and not the `Array.isArray()`.

As far as I see it, the purpose of `react-web` is to provide the exact same API as `react-native` but with a different target.

In this case a user would expect an Array of styles to work regardless of the underlying implementation of the component (they shouldn't have to care about the target, just their react-native code), especially in this case where the component only breaks under certain conditions (which is clearly unexpected).

I think a better fix is to **always** process styles, but return the functors results before doing so.

**Comment by gre** [comment]
`extendCreateElement` seems to overrides `React.createElement` which is going to always be called when you write JSX (`<Image/>` JSX is transformed into a call to `React.createElement(Image, props)`), so AFAIK it will always happen when you write `<Image/>`, this is why I don't understand this.

**As you said, react-dom does not support array of style, and react-web shouldn't alter this fact, otherwise it means breaking compatibility with any other react(-dom) library.** This should only be fixed for react-web "compatible" components. Now how to detect this belonging to category is the whole question, but I disagree with the idea that this should happen for all elements that goes into `createElement` whatever if it belongs to react-web or not.

In react-native's context, `style` is only consumed for React Native UI components (that goes into RN rendering) but it **does not** happen for non RN UI Component like: `<Connect/>` of react-redux, `<Route>` of react-router, `<Text>` of `react-canvas` (just to take some simple examples).

**Comment by pmead** [comment]
I think its possible that we view the role of react-web differently.
My view is that it is a layer of abstraction that allows the development of a primarily react-native application with a html output. 
That html output could be supported by react-dom or angular or anything else, it doesn't actually matter. It just so happens that it maps quite well to react-dom.

However I do agree that the underlying render library shouldn't be broken due to invasive changes, but I don't think having consistent react-native features (+ syntactic sugar) and not causing breaks to the react-dom library are mutually exclusive.

In the same way react-web translates `<Image/>` to a valid react-dom element I expect style arrays `[{},{}]` to translate to a valid react-dom style object, the whole point of react-web is to do this translation.

As for `react-canvas` it takes an object (as you would expect from sane developers, they have simply mimicked react-dom's api) so as long as we translate to something react-dom can handle there's no problem there. Is there a gist of breaking code that you could provide? I genuinely have no breaking issues when using react-canvas and processed styles together.

Anyway it feels like we're getting slightly off topic, I'll look to see if I can find a solution that can be agreed upon.

I found there are other breaks with `<Image/>` and arrays of styles that my fix doesn't fix anyway, e.g. when the style becomes a div[ it just adds the background image](https://github.com/taobaofed/react-web/blob/master/Libraries/Image/Image.web.js#L37) styles as if the styles are always an object, so you can end up with an array of styles with attributes on the array :\.

Also in regards to "why doesn't the style processing apply to <Image/> itself?" what would that even look like? Custom components are **not** elements, they return elements.
To make it process the style property passed to a native component we'd have to do the processing in an `extendCreateClass` call not `extendCreateElement`.

**Comment by gre** [comment]
as far as I remember, one of the problem I encounter with react-canvas was when using `<Text style={{ lineHeight: 10 }} />` where 10 gets converted to a "10px" format.
I can try to put a full example to repro this if you want it.

**Comment by pmead** [comment]
No need, that makes perfect sense. I wouldn't want _that_ to happen either, I am only talking about the flattening step.

However I have found that [fixing these lines](https://github.com/taobaofed/react-web/blob/master/Libraries/Image/Image.web.js#L37) allows resize mode to work and arrays of styles get applied to the `<Image/>` correctly for the `<div/>`.

Which makes it even more bizarre that it doesn't work in the case of `<img/>`

**Comment by gre** [comment]
yeah i'm not getting why it doesn't in `<img/>`

**Comment by pmead** [comment]
Ok I've done some digging and found that its actually another react-native library which expects to manipulate the style of the children it wraps.

What essentially happens is the image.props.style gets processed and flattened and then its parent component decides it needs more styles adding to it, which won't get reprocessed (because the element is already created) and when `<img>` is created it will get these new _not_ flattened styles.

Wrapping Component Render -> Create element (Image) -> Flattens image.styles --> wrapping component pushes updates each Child's styles --> Image Render --> create element (img)...

This is reasonable behavior for any react-native library, even react-web does it in <Image/> when it creates a div, only when it creates a div element it uses the view constructor so the styles get processed again (which is why the div part works).
